name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Path
        run: pwd

      - name: Make env var ENV_DOMAIN_URL
        run: echo ENV_DOMAIN_URL=${{ secrets.DEV_DOMAIN_URL }}  > .env

      - name: Make env var ENV_AUTH_SERVICE_URL
        run: echo ENV_AUTH_SERVICE_URL="${{ secrets.DEV_AUTH_SERVICE_URL }}"  >> .env

      - name: Make env var ENV_SSL_SERT_ROOT
        run: echo ENV_SSL_SERT_ROOT="${{ secrets.DEV_SSL_SERT_ROOT }}"  >> .env

      - name: Down auth container
        run: docker compose down

      - name: Up auth container
        run: docker compose up -d

