name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Path
        run: pwd

      - name: Down auth container
        run: docker compose down

      - name: Up auth container
        run: docker compose up -d

